# Generated by Django 2.2.24 on 2021-11-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_remove_estudiante_clases'),
        ('clases', '0003_remove_clase_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estudiantes',
            field=models.ManyToManyField(related_name='Clases', to='estudiantes.Estudiante'),
        ),
    ]
