# Generated by Django 2.2.24 on 2021-11-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_clase_estudiantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='estudiantes',
        ),
    ]
