# Generated by Django 2.2.24 on 2021-11-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_remove_clase_estudiantes'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='clases',
            field=models.ManyToManyField(related_name='Estudiantes', to='clases.Clase'),
        ),
    ]
