# Generated by Django 2.2.24 on 2021-11-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_estudiante_clases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='clases',
        ),
    ]
