# Generated by Django 2.2.24 on 2021-11-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0005_remove_clase_estudiantes'),
        ('estudiantes', '0003_remove_estudiante_clases'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='clases',
            field=models.ManyToManyField(related_name='estudiantes', to='clases.Clase'),
        ),
    ]
